create table if not exists public.remote_logs (
    id bigint generated by default as identity primary key,
    device_id text not null default 'unknown',
    status text not null default 'Unknown',
    source text not null default 'unknown',
    created_at timestamptz not null default now(),
    payload jsonb null
);

create index if not exists remote_logs_created_at_idx
    on public.remote_logs (created_at desc);

create index if not exists remote_logs_device_id_idx
    on public.remote_logs (device_id);
